name: Pull Request
on:
  push:
  pull_request:
    types: [opened reopened syncronize]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v1
      - name: Lint code
        run: yarn run lint:eslint
      - name: Lint styles
        run: yarn run lint:stylelint
      - name: Check formatting
        run: yarn run prettier:check
      - name: Check spelling
        run: yarn run cspell
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Test
        run: yarn run test
  chromatic:
    name: Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          buildScriptName: build:storybook
