name: Release
on:
  push:
    tags:
      - '*'
jobs:
  storybook:
    name: Storybook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Lint code
        run: yarn run lint:eslint
      - name: Lint styles
        run: yarn run lint:stylelint
      - name: Check formatting
        run: yarn run prettier:check
      - name: Test
        run: yarn run test
      - name: Build
        run: yarn build:storybook
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          BRANCH: gh-pages
          FOLDER: storybook-static
